### ISSUE TITLE
honeypot checker

### ISSUE THREAD

**Issue by ravenflores** [malvaphe/Crypto-Honeypot-Detector#1] opened 2022-07-03 03:31 UTC
I used safe analyzer to check a honeypot  there but here  its not honeypot can you improve its something like it

**Comment by malvaphe** [comment] 2022-07-03 11:26
> I used safe analyzer to check a honeypot there but here its not honeypot can you improve its something like it

I didn't quite understand what the problem is. Could you provide more information? Chain, Dex, Token address (should or shouldn't it be a honeypot?). Thank you :)

**Comment by ravenflores** [comment] 2022-08-22 05:24
![image](https://user-images.githubusercontent.com/66240114/185844976-cbdb4c29-cb8f-4690-8235-b561f6a4ec2f.png)

this has some problem I think  it doesn't return buy and sell tax that's what I need.
 example is poocoin  have enough liquidity but still its having error

**Comment by malvaphe** [comment] 2022-08-22 06:22
As written in the README, you have to deploy the contract to be able to use the honeypot detector...
![Screenshot_1](https://user-images.githubusercontent.com/49184710/185852675-07d1802e-9756-478d-beda-fa55aa9a3b1d.png)

**Comment by ravenflores** [comment] 2022-08-22 06:27
![image](https://user-images.githubusercontent.com/66240114/185853172-ef4fcc5a-5ba0-4469-99d2-4608253693f5.png)
already did sir hm bnb is required btw 
https://bscscan.com/address/0xd0fe451fb5db5f763cad3fb7f60cb48ded8735f2#code
u can check it here

**Comment by malvaphe** [comment] 2022-08-22 06:33
You have to transfer some WBNBs as well.

**Comment by ravenflores** [comment] 2022-08-22 06:36
> You have to transfer some WBNBs as well.


![image](https://user-images.githubusercontent.com/66240114/185855221-fc869c48-ada5-46ed-a072-384b28006c3c.png)
it already have .1 bnb i don't see any problem here tho

**Comment by malvaphe** [comment] 2022-08-22 06:49
You only transferred BNB, not WBNB.
Example of a valid contract:
![Screenshot_2](https://user-images.githubusercontent.com/49184710/185856878-d60d02cc-c79c-4739-b511-11b5534aecab.png)
Your contract:
![Screenshot_3](https://user-images.githubusercontent.com/49184710/185856939-8fca3f68-afb6-47d5-ae94-2e7deb265aa1.png)

**Comment by ravenflores** [comment] 2022-08-22 07:01
finally works damn thanks you so much sir

**Closed as completed** 2022-08-22 07:34 UTC
